# Generated by Django 4.1.3 on 2023-09-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="disaster"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_main_focus", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
