# Generated by Django 4.1.3 on 2023-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disaster",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="disaster/"),
        ),
    ]
