# Generated by Django 4.1.3 on 2023-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disaster",
            name="closed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
