# Generated by Django 4.1.3 on 2023-09-15 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                ("surname", models.CharField(max_length=255, verbose_name="اللقب")),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان السكن",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="المدينة"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]", "Only numbers are allowed."
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "email_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="البريد الالكتروني",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "انثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "photograph",
                    models.ImageField(
                        blank=True, null=True, upload_to="mafqood", verbose_name="صورة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "InActive")],
                        default="active",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
