# Generated by Django 4.1.3 on 2023-09-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="about_volunteer",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="نبذة عن المتطوع"
            ),
        ),
    ]
