# Generated by Django 4.1.3 on 2023-09-16 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0002_volunteer_about_volunteer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="city",
            field=models.CharField(max_length=255, verbose_name="المدينة"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="contact_number",
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]", "Only numbers are allowed."
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="email_address",
            field=models.CharField(max_length=255, verbose_name="البريد الالكتروني"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("inactive", "InActive"),
                ],
                default="new",
                max_length=50,
                null=True,
            ),
        ),
    ]
