# Generated by Django 4.1.3 on 2023-09-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "volunteer",
            "0003_alter_volunteer_city_alter_volunteer_contact_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "InActive"),
                        ],
                        default="new",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="photograph",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="volunteer",
                verbose_name="صورة المتطوع",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="assigned_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteers",
                to="volunteer.team",
                verbose_name="فريق العمل",
            ),
        ),
    ]
