# Generated by Django 4.1.3 on 2023-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0004_team_alter_volunteer_photograph_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="photograph",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="volunteers",
                verbose_name="صورة المتطوع",
            ),
        ),
    ]
