# Generated by Django 4.1.3 on 2023-09-13 21:26

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disaster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mafqood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الاسم"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="اللقب"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="العمر"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان السكن",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="المدينة"
                    ),
                ),
                (
                    "contact_number",
                    phone_field.models.PhoneField(
                        blank=True, max_length=31, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "ذكر"), ("female", "انثى")],
                        max_length=10,
                        null=True,
                        verbose_name="جنس",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="الوزن"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="الطول"),
                ),
                (
                    "distinct_feature",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ملامح مميزة",
                    ),
                ),
                (
                    "blod_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A", "-"),
                            ("B+", "B+"),
                            ("B", "B-"),
                            ("AB", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="فصيلة الدم",
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاختفاء"
                    ),
                ),
                (
                    "last_contact_details",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="معلومات عن اخر لقاء",
                    ),
                ),
                (
                    "any_other_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="معلومات اضافية"
                    ),
                ),
                (
                    "photograph",
                    models.ImageField(
                        blank=True, null=True, upload_to="mafqood", verbose_name="صورة"
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الاسم"
                    ),
                ),
                (
                    "reporter_surname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="اللقب"
                    ),
                ),
                (
                    "reporter_contact_number",
                    phone_field.models.PhoneField(
                        blank=True, max_length=31, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "reporter_contact_number_2",
                    phone_field.models.PhoneField(
                        blank=True,
                        max_length=31,
                        null=True,
                        verbose_name="رقم الهاتف 2",
                    ),
                ),
                (
                    "reporter_relation_to_missing",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الصلة للمفقود",
                    ),
                ),
                (
                    "reporter_city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="المدينة"
                    ),
                ),
                (
                    "reporter_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان السكن",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("missing", "Missing"),
                            ("found", "Found"),
                            ("deceased", "Deceased"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missings",
                        to="disaster.disaster",
                    ),
                ),
            ],
        ),
    ]
