# Generated by Django 4.1.3 on 2023-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mafqood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nid", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "family_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_family_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_family_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("missing", "Missing"),
                            ("found", "Found"),
                            ("deceased", "Deceased"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                (
                    "last_contact_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
