# Generated by Django 4.1.3 on 2023-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mafqood",
            name="last_contact_details",
        ),
        migrations.AddField(
            model_name="mafqood",
            name="clothing",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ملابس"
            ),
        ),
    ]
