# Generated by Django 4.1.3 on 2023-09-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("disaster", "__first__"),
        ("mafqood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafqood",
            name="disaster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missings",
                to="disaster.disaster",
            ),
        ),
    ]
