# Generated by Django 4.1.3 on 2023-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0002_mafqood_disaster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mafqood",
            name="father_family_name",
        ),
        migrations.RemoveField(
            model_name="mafqood",
            name="father_father_name",
        ),
        migrations.RemoveField(
            model_name="mafqood",
            name="mother_family_name",
        ),
        migrations.RemoveField(
            model_name="mafqood",
            name="mother_father_name",
        ),
        migrations.RemoveField(
            model_name="mafqood",
            name="nid",
        ),
        migrations.RemoveField(
            model_name="mafqood",
            name="telephone",
        ),
        migrations.AddField(
            model_name="mafqood",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="any_other_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="contact_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="distinct_feature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="photograph",
            field=models.ImageField(blank=True, null=True, upload_to="mafqoodeen/"),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="reporter_contact_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="reporter_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="reporter_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="reporter_relation_to_missing",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
