# Generated by Django 4.1.3 on 2023-09-14 09:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0003_alter_mafqood_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafqood",
            name="reporter_email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="البريد الالكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="mafqood",
            name="reporter_contact_number_2",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="رقم الهاتف اضافي",
            ),
        ),
    ]
