# Generated by Django 4.1.3 on 2023-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0003_remove_mafqood_father_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mafqood",
            name="photograph",
            field=models.ImageField(blank=True, null=True, upload_to="mafqood"),
        ),
    ]
