# Generated by Django 4.1.3 on 2023-09-13 16:15

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0004_alter_mafqood_photograph"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafqood",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "ذكر"), ("female", "انثى")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mafqood",
            name="contact_number",
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
