# Generated by Django 4.1.3 on 2023-09-13 16:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0005_mafqood_gender_alter_mafqood_contact_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mafqood",
            old_name="last_contact",
            new_name="last_contact_date",
        ),
        migrations.AddField(
            model_name="mafqood",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="blod_type",
            field=models.CharField(
                blank=True,
                choices=[("male", "ذكر"), ("female", "انثى")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="report_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="report_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="reporter_contact_number_2",
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name="mafqood",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("A+", "A+"),
                    ("A", "-"),
                    ("B+", "B+"),
                    ("B", "B-"),
                    ("AB", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mafqood",
            name="reporter_contact_number",
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
