# Generated by Django 4.1.3 on 2023-09-14 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mafqood",
            "0005_alter_mafqood_gender_alter_mafqood_last_contact_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mafqood",
            name="contact_number",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]", "Only numbers are allowed."
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="mafqood",
            name="reporter_contact_number",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]", "Only numbers are allowed."
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="mafqood",
            name="reporter_contact_number_2",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]", "Only numbers are allowed."
                    )
                ],
                verbose_name="رقم الهاتف اضافي",
            ),
        ),
    ]
