# Generated by Django 4.1.3 on 2023-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0006_alter_mafqood_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mafqood",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("missing", "Missing"),
                    ("found", "Found"),
                    ("deceased", "Deceased"),
                ],
                default="missing",
                max_length=50,
                null=True,
            ),
        ),
    ]
