# Generated by Django 4.1.3 on 2023-09-15 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("disaster", "0002_disaster_closed"),
        ("mafqood", "0007_alter_mafqood_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الاسم"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="اللقب"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="العمر"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان السكن",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="المدينة"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]", "Only numbers are allowed."
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الموقع الحالي",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "انثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="الوزن"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="الطول"),
                ),
                (
                    "blod_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A", "-"),
                            ("B+", "B+"),
                            ("B", "B-"),
                            ("AB", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="فصيلة الدم",
                    ),
                ),
                (
                    "clothing",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="ملابس"
                    ),
                ),
                (
                    "distinct_feature",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ملامح مميزة",
                    ),
                ),
                (
                    "any_other_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="معلومات اضافية"
                    ),
                ),
                (
                    "photograph",
                    models.ImageField(
                        blank=True, null=True, upload_to="mafqood", verbose_name="صورة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("injured", "Injured"),
                            ("deceased", "Deceased"),
                            ("buried", "Buried"),
                            ("idp", "IDP"),
                        ],
                        default="missing",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="disaster.disaster",
                    ),
                ),
            ],
        ),
    ]
