# Generated by Django 4.1.3 on 2023-09-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0008_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("injured", "Injured"),
                    ("deceased", "Deceased"),
                    ("buried", "Buried"),
                    ("idp", "IDP"),
                ],
                default="idp",
                max_length=50,
                null=True,
                verbose_name="الوضع الحالي",
            ),
        ),
    ]
