# Generated by Django 4.1.3 on 2023-09-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0009_alter_person_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafqood",
            name="matched_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched",
                to="mafqood.person",
            ),
        ),
    ]
