# Generated by Django 4.1.3 on 2023-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0012_alter_mafqood_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafqood",
            name="update_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red_crescent", "Red Crescent"),
                    ("fronsic_office", "Forensic Office"),
                    ("hospital", "Hospital & Medical Center"),
                    ("mafqood", "Mafqood"),
                    ("other", "Other Sources"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mafqood",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("missing", "Missing"),
                    ("found", "Found"),
                    ("deceased", "Deceased"),
                    ("injured", "Injured"),
                    ("buried", "Buried"),
                    ("idp", "IDP"),
                ],
                default="missing",
                max_length=50,
                null=True,
            ),
        ),
    ]
