# Generated by Django 4.1.3 on 2023-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0013_mafqood_update_by_mafqood_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mafqood",
            name="photograph",
            field=models.ImageField(
                blank=True, null=True, upload_to="mafqoods", verbose_name="صورة"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="photograph",
            field=models.ImageField(
                blank=True, null=True, upload_to="persons", verbose_name="صورة"
            ),
        ),
    ]
