# Generated by Django 4.1.3 on 2023-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0015_person_document_person_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafqood",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="اسم الاب"
            ),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="grandfather_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="اسم الجد  (والد الأب)"
            ),
        ),
        migrations.AddField(
            model_name="mafqood",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="اسم الام"
            ),
        ),
    ]
