# Generated by Django 4.1.3 on 2023-09-27 22:25

from django.db import migrations, models


def update_full_name(apps, schema_editor):
    Mafqood = apps.get_model("mafqood", "Mafqood")
    for m in Mafqood.objects.all():
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0016_mafqood_father_name_mafqood_grandfather_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafqood",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="الاسم كامل"
            ),
        ),
    ]
