# Generated by Django 4.1.3 on 2023-09-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0018_mafqood_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mafqood",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comments"),
        ),
    ]
