# Generated by Django 4.1.3 on 2023-09-27 22:25

from django.db import migrations, models
from mafqood.models import Mafqood


def update_full_name(apps, schema_editor):
    for m in Mafqood.objects.all():
        m.full_name = m.get_full_name()
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mafqood", "0019_alter_mafqood_comment"),
    ]

    operations = [
        migrations.RunPython(update_full_name),
    ]
